name: Publish

on:
  workflow_dispatch:
    inputs:
      tag:
        description: 'Tag to publish'
        type: choice
        required: true
        # default: 2025
        options:
          - '2025'
      latest:
        description: 'Additionally tag image as latest'
        type: boolean
        required: true
        default: false

env:
  IMAGE_NAME: tahv/mayapy

jobs:
  build-push:
    name: Push image to Docker Hub
    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write
      attestations: write
    steps:
      - uses: actions/checkout@v4

      - name: Login to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Extract metadata
        id: meta
        uses: docker/metadata-action@v5
        with:
          images: ${{ env.IMAGE_NAME }}
          tags: |
            type=raw,value=${{ inputs.tag }}
            type=raw,value=latest,enable=${{ inputs.latest }}

      - name: Build and push
        id: push
        uses: docker/build-push-action@v5
        with:
          push: true
          context: ./${{ input.tag }}
          tags: ${{ steps.meta.outputs.tags }}
          labels: ${{ steps.meta.outputs.labels }}

      - name: Generate artifact attestation
        uses: actions/attest-build-provenance@v1
        with:
          subject-name: ${{ env.IMAGE_NAME }}
          subject-digest: ${{ steps.push.outputs.digest }}
          push-to-registry: true
